// language.js - NO ICON, only auto-translate from dashboard choice
const COUNTRY_LANG={Kenya:{main:"en",alt:["sw"]},Uganda:{main:"en",alt:["sw","lg"]},Tanzania:{main:"sw",alt:["en"]},Rwanda:{main:"en",alt:["sw"]},"Guinea-Bissau":{main:"pt",alt:["en"]},DRC:{main:"fr",alt:["en"]},"South Africa":{main:"en",alt:[]},Nigeria:{main:"en",alt:[]},Ghana:{main:"en",alt:[]},Ethiopia:{main:"en",alt:[]},Zimbabwe:{main:"en",alt:[]},Zambia:{main:"en",alt:[]},Botswana:{main:"en",alt:[]},Namibia:{main:"en",alt:[]},USA:{main:"en",alt:[]},Canada:{main:"en",alt:[]},UK:{main:"en",alt:[]},Australia:{main:"en",alt:[]},India:{main:"en",alt:[]}};

const TRANSLATIONS={
en:{welcome:"Welcome",requirements:"Requirements",application:"Application",members:"Members",helpline:"Helpline",laws:"Laws",home:"Home",administration:"ADMINISTRATION CHANNEL",tap_message:"Tap to message Administration",type_message:"Type message...",welcome_back:"Welcome Back,",subtitle:"Member Portal • Secure Access",membership_status:"Membership Status",lodge:"Lodge",member_since:"Member Since",full_name:"Full Name",email_address:"Email Address",phone_number:"Phone Number",country:"Country",area_interest:"Area of Interest",lodge_info:"Lodge Information",lodge_desc:"Access meeting schedules, lodge announcements, and member activities.",latest_ann:"Latest Announcements",support:"Membership Support",support_desc:"Contact your Lodge Director for guidance and fraternity assistance.",loading:"Loading...",logout:"Logout"},
sw:{welcome:"Karibu",requirements:"Mahitaji",application:"Maombi",members:"Wanachama",helpline:"Msaada",laws:"Sheria",home:"Nyumbani",administration:"CHIMBO LA UTAWALA",tap_message:"Gusa kutuma ujumbe kwa Utawala",type_message:"Andika ujumbe...",welcome_back:"Karibu Tena,",subtitle:"Portal ya Mwanachama • Ufikiaji Salama",membership_status:"Hali ya Uanachama",lodge:"Lodge",member_since:"Mwanachama Tangu",full_name:"Jina Kamili",email_address:"Barua Pepe",phone_number:"Namba ya Simu",country:"Nchi",area_interest:"Eneo la Maslahi",lodge_info:"Taarifa za Lodge",lodge_desc:"Pata ratiba za mikutano na matangazo.",latest_ann:"Matangazo ya Hivi Karibuni",support:"Msaada wa Uanachama",support_desc:"Wasiliana na Mkurugenzi wako kwa mwongozo.",loading:"Inapakia...",logout:"Toka"},
lg:{welcome:"Twanirizza",requirements:"Ebyetaago",application:"Okusaba",members:"Bammemba",helpline:"Obuyambi",laws:"Amateeka",home:"Awaka",administration:"EKITONGOLE KY'OBUYINZA",tap_message:"Nyiga okutumira obubaka",type_message:"Wandiika obubaka...",welcome_back:"Twanirizza,",subtitle:"Portal y'Obwammemba",membership_status:"Embeera y'Obwammemba",lodge:"Lodge",member_since:"Mmemba Okuva",full_name:"Amannya Goonna",email_address:"Email",phone_number:"Namba y'Essimu",country:"Ensi",area_interest:"Ekitundu",lodge_info:"Ebikwata ku Lodge",lodge_desc:"Funa enteekateeka z'ebimeeting.",latest_ann:"Ebilangiriro",support:"Obuyambi",support_desc:"Tukirira Director wo.",loading:"Kiteekebwa...",logout:"Fuluma"},
fr:{welcome:"Bienvenue",requirements:"Exigences",application:"Application",members:"Membres",helpline:"Assistance",laws:"Lois",home:"Accueil",administration:"CANAL D'ADMINISTRATION",tap_message:"Appuyez pour écrire à l'Administration",type_message:"Écrire un message...",welcome_back:"Bon Retour,",subtitle:"Portail des Membres • Accès Sécurisé",membership_status:"Statut d'Adhésion",lodge:"Loge",member_since:"Membre Depuis",full_name:"Nom Complet",email_address:"Email",phone_number:"Téléphone",country:"Pays",area_interest:"Centre d'Intérêt",lodge_info:"Infos Loge",lodge_desc:"Accédez aux horaires et annonces.",latest_ann:"Dernières Annonces",support:"Support",support_desc:"Contactez votre Directeur.",loading:"Chargement...",logout:"Déconnexion"},
pt:{welcome:"Bem-vindo",requirements:"Requisitos",application:"Aplicação",members:"Membros",helpline:"Ajuda",laws:"Leis",home:"Início",administration:"CANAL DE ADMINISTRAÇÃO",tap_message:"Toque para enviar mensagem à Administração",type_message:"Digite a mensagem...",welcome_back:"Bem-vindo de Volta,",subtitle:"Portal do Membro",membership_status:"Status",lodge:"Loja",member_since:"Membro Desde",full_name:"Nome Completo",email_address:"Email",phone_number:"Telefone",country:"País",area_interest:"Área",lodge_info:"Info Loja",lodge_desc:"Acesse horários.",latest_ann:"Últimos Anúncios",support:"Suporte",support_desc:"Contate seu Diretor.",loading:"Carregando...",logout:"Sair"}
};

function getLang(){return localStorage.getItem('siteLang')||COUNTRY_LANG[localStorage.getItem('selectedCountry')||'Kenya'].main||'en';}
function tr(k){const l=getLang();return (TRANSLATIONS[l]&&TRANSLATIONS[l][k])||TRANSLATIONS.en[k]||k;}
function applyLang(){
  document.querySelectorAll('[data-i18n]').forEach(el=>{el.innerText=tr(el.dataset.i18n);});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>{el.placeholder=tr(el.dataset.i18nPlaceholder);});
}
document.addEventListener('DOMContentLoaded',applyLang);
