class LodgeNotifier{
 constructor(){this.unreadCount=0;this.audio=new Audio('/sounds/notification.mp3');this.audio.volume=0.7;window.speechSynthesis.getVoices();setTimeout(()=>window.speechSynthesis.getVoices(),500);}
 speak(t){try{window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=0.92;u.pitch=1.05;const v=window.speechSynthesis.getVoices();const p=v.find(x=>x.name.includes('Google UK English Female')||x.name.includes('Zira')||x.name.toLowerCase().includes('female'))||v[0];if(p)u.voice=p;window.speechSynthesis.speak(u);}catch(e){}}
 async showSystemNotification(title,body){try{if('serviceWorker' in navigator){const r=await navigator.serviceWorker.ready;r.showNotification(title,{body,icon:'masonic-G.png',badge:'masonic-G.png',vibrate:[200,100,200],tag:'mff-lodge',renotify:true});return;}}catch(e){}if('Notification' in window&&Notification.permission==="granted"){try{new Notification(title,{body,icon:'masonic-G.png'});}catch(e){}}}
 async setAppIconBadge(count){this.unreadCount=count;localStorage.setItem("appBadgeCount",count);localStorage.setItem("globalChatBadge_count",count);localStorage.setItem("notifCount_count",count);const b1=document.getElementById("globalChatBadge");const b2=document.getElementById("notifCount");if(b1){b1.textContent=count>99?"99+":count;b1.style.display=count>0?"grid":"none";}if(b2){b2.textContent=count>99?"99+":count;b2.style.display=count>0?"grid":"none";}if('setAppBadge' in navigator){try{if(count>0)await navigator.setAppBadge(count);else await navigator.clearAppBadge();}catch(e){}}document.title=count>0?`(${count}) MFF Lodge`:"MFF Lodge";}
 showPopup(title,message,type){const old=document.getElementById("lodgePopup");if(old)old.remove();const p=document.createElement("div");p.id="lodgePopup";p.style=`position:fixed;top:80px;right:20px;left:20px;max-width:350px;margin-left:auto;background:linear-gradient(145deg,#142238,#0b1728);border:1px solid #d4af37;border-radius:16px;padding:15px;display:flex;gap:12px;z-index:9999;box-shadow:0 15px 40px rgba(0,0,0,.6);`;p.innerHTML=`<div style="width:45px;height:45px;background:rgba(212,175,55,.2);border-radius:12px;display:grid;place-items:center;color:#d4af37;"><i class="fa ${type==="announcement"?"fa-bullhorn":"fa-comments"}"></i></div><div style="flex:1;"><div style="font-weight:700;color:white;font-size:14px;">${title}</div><div style="font-size:12px;color:#ccc;margin-top:4px;">${message}</div></div><div onclick="this.parentElement.remove()" style="color:#777;cursor:pointer;"><i class="fa fa-times"></i></div>`;document.body.appendChild(p);setTimeout(()=>{if(p.parentElement)p.remove();},6000);}
}
const notifier=new LodgeNotifier();window.LodgeNotifier=notifier;
const saved=localStorage.getItem("appBadgeCount");if(saved&&parseInt(saved)>0){setTimeout(()=>notifier.setAppIconBadge(parseInt(saved)),1000);}
